version: '3'
services:
  api:
    # TODO - Need a way to make the ECR url to be read from env variables (probably dinamically generate docker-compose)
    image: 705750910119.dkr.ecr.us-west-2.amazonaws.com/aclu:latest
    container_name: aclu-api
    environment:
      - MONGO_HOST=db
    ports:
      - "50050:50050"
    links:
      - db
  db:
    image: mongo:3.5.11
    container_name: aclu-db
    ports:
      - "27017"
