version: '3'
services:
  api:
    # $IMAGES_REPO_URL variable should have been setup by TF during provisioning
    image: aclu:latest
    container_name: aclu-api
    environment:
      - MONGO_HOST=db
    ports:
      - "50050:50050"
    links:
      - db
  db:
    image: mongo:3.5.11
    container_name: aclu-db
    ports:
      - "27017"
