version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: aclu-api
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DBNAME=${MONGO_DBNAME}
    ports:
      - "50050:50050"
    volumes:
      - ./api:/src/api
    links:
      - db
  db:
    container_name: aclu-db
    image: 'bitnami/mongodb:4.0.9'
    ports:
      - "27017:27017"
    volumes:
      - aclu-db:/bitnami
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DBNAME}
volumes:
  aclu-db:
    external: true
