<template>
  <div id="about-page">
    <div id="about-page-content">
      <h1>About Holoholo</h1>
    </div>
    <div id="about-page-text">
      Holoholo is an open-source web app designed to help you better
      know your rights while out and about on O‘ahu. It gives you
      information about where you are, whether the space is public or
      private land, and your rights in various spaces.
    </div>
    <div id="about-page-text">
      <strong>IMPORTANT TO KNOW:</strong>
      <ul>
        <li>
          The information generated by Holoholo is general in nature,
          and not meant to be legal advice.
        </li>
        <li>
          The system relies on GPS coordinates for your device, which
          can be inaccurate. When in doubt, always follow the directions
          of available signs and law enforcement.
        </li>
        <li>
          The system is designed to map your location only on demand
          and anonymously, and does not require log in or store any
          session or location information that could be traced to an
          individual.
        </li>
        <li>
          While effort is made to ensure that information
          like park closure hours is correct, things may change in the
          field more quickly. Always obey posted signs and law enforcement
          directions. Reports of errors or omissions are appreciated!
          Please send reports to holoholo@acluhawaii.org
        </li>
        <li>
          With help from the American Civil Liberties Union of
          Hawai‘i, Holoholo was developed by the all-volunteer Code for
          Hawai‘i brigade in 2018-2019. The name and the webapp are
          published under and MIT open source license:
          https://en.wikipedia.org/wiki/MIT_License
        </li>
      </ul>
      <md-button>
        <router-link to="/licenses">
          <span class="md-list-item-text">open source licenses</span>
        </router-link>
      </md-button>
    </div>
  </div>
</template>

<script>
export default {
  name: "About"
};
</script>

<style scoped>
#about-page {
  background-color: #fafafa;
  text-align: center;
  align-content: center;
}
#about-page-text {
  text-align: left;
  align-content: left;
}
#about-page-content {
  width: 80%;
  display: inline-block;
}
</style>
