version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    container_name: aclu-api
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ../api:/src/api
    links:
      - db
  db:
    build: ./db
    container_name: aclu-db
    ports:
        - 127.0.0.1:27017:27017
